export interface University {
    id: number;
    name: string;
    country: string; 
    logo: string; 
    website: string; 
    partnershipType: string;
    displayOrder: number; 
    showOnHomepage: boolean; 
    homepageOrder?: number; 
}

/**
 * Helper function to get universities sorted by displayOrder
 */
export function getUniversitiesSorted(universities: University[]): University[] {
    return [...universities].sort((a, b) => a.displayOrder - b.displayOrder);
}

/**
 * Helper function to get universities for homepage (filtered and sorted)
 */
export function getHomepageUniversities(universities: University[]): University[] {
    return universities
        .filter(uni => uni.showOnHomepage)
        .sort((a, b) => {
            // Sort by homepageOrder if available, otherwise by displayOrder
            const orderA = a.homepageOrder ?? a.displayOrder;
            const orderB = b.homepageOrder ?? b.displayOrder;
            return orderA - orderB;
        });
}

/**
 * Helper function to get universities by country
 */
export function getUniversitiesByCountry(universities: University[], country: string): University[] {
    return getUniversitiesSorted(universities.filter(uni => uni.country === country));
}


export const universitiesData: University[] = [
    {
        id: 1,
        name: "Texas State University",
        country: "usa",
        logo: "/universities/usa/Texas_State_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 1,
        showOnHomepage: false,
    },
    {
        id: 2,
        name: "Colorado State University",
        country: "usa",
        logo: "/universities/usa/Colorado_State_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 2,
        showOnHomepage: false,
    },
    {
        id: 3,
        name: "University of Arizona",
        country: "usa",
        logo: "/universities/usa/University_Of_Arizona_usa.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 3,
        showOnHomepage: true,
        homepageOrder: 11,
    },
    {
        id: 4,
        name: "Queens College",
        country: "usa",
        logo: "/universities/usa/Queens_College.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 4,
        showOnHomepage: false,
    },
    {
        id: 5,
        name: "Berkeley College",
        country: "usa",
        logo: "/universities/usa/Berkeley_College.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 5,
        showOnHomepage: false,
    },
    {
        id: 6,
        name: "Montclair State University",
        country: "usa",
        logo: "/universities/usa/Montclair_State_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 6,
        showOnHomepage: false,
    },
    {
        id: 7,
        name: "Long Island University",
        country: "usa",
        logo: "/universities/usa/Long_Island_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 7,
        showOnHomepage: false,
    },
    {
        id: 8,
        name: "The University Of Oklahoma",
        country: "usa",
        logo: "/universities/usa/The_University_Of_Oklahoma.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 8,
        showOnHomepage: false,
    },
    {
        id: 9,
        name: "University Of Northern Iowa",
        country: "usa",
        logo: "/universities/usa/University_Of_Northern_Iowa_usa.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 9,
        showOnHomepage: true,
        homepageOrder: 12,
    },
    {
        id: 10,
        name: "San Francisco State University",
        country: "usa",
        logo: "/universities/usa/San_Francisco_State_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 10,
        showOnHomepage: false,
    },
    {
        id: 11,
        name: "University Of Bridgeport",
        country: "usa",
        logo: "/universities/usa/University_Of_Bridgeport.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 11,
        showOnHomepage: false,
    },
    {
        id: 12,
        name: "William Paterson University",
        country: "usa",
        logo: "/universities/usa/William_Paterson_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 12,
        showOnHomepage: false,
    },
    {
        id: 13,
        name: "Illinois State University",
        country: "usa",
        logo: "/universities/usa/Illinois_State_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 13,
        showOnHomepage: false,
    },
    {
        id: 14,
        name: "University of North Texas",
        country: "usa",
        logo: "/universities/usa/University_Of_North_Texas.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 14,
        showOnHomepage: false,
    },
    {
        id: 15,
        name: "Ashland University",
        country: "usa",
        logo: "/universities/usa/Ashland_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 15,
        showOnHomepage: false,
    },
    {
        id: 16,
        name: "Saint Louis University",
        country: "usa",
        logo: "/universities/usa/Saint_Louis_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 16,
        showOnHomepage: false,
    },
    {
        id: 17,
        name: "Murray State University",
        country: "usa",
        logo: "/universities/usa/Murray_State_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 17,
        showOnHomepage: false,
    },
    {
        id: 18,
        name: "Florida Atlantic University",
        country: "usa",
        logo: "/universities/usa/Florida_Atlantic_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 18,
        showOnHomepage: false,
    },
    {
        id: 19,
        name: "Oregon State University",
        country: "usa",
        logo: "/universities/usa/Oregon_State_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 19,
        showOnHomepage: false,
    },
    {
        id: 20,
        name: "Emporia State University",
        country: "usa",
        logo: "/universities/usa/Emporia_State_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 20,
        showOnHomepage: false,
    },
    {
        id: 21,
        name: "Mercy University",
        country: "usa",
        logo: "/universities/usa/Mercy_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 21,
        showOnHomepage: false,
    },
    {
        id: 22,
        name: "Youngstown State University",
        country: "usa",
        logo: "/universities/usa/Youngstown_State_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 22,
        showOnHomepage: true,
        homepageOrder: 13,
    },
    {
        id: 23,
        name: "London South Bank University",
        country: "uk",
        logo: "/universities/uk/London_South_Bank_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 23,
        showOnHomepage: false,
    },
    {
        id: 24,
        name: "University of Roehampton",
        country: "uk",
        logo: "/universities/uk/University_of_Roehampton.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 24,
        showOnHomepage: false,
    },
    {
        id: 25,
        name: "Ravensbourne University London",
        country: "uk",
        logo: "/universities/uk/Ravensbourne_University_London.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 25,
        showOnHomepage: true,
        homepageOrder: 14,
    },
    {
        id: 26,
        name: "University of South Wales",
        country: "uk",
        logo: "/universities/uk/University_Of_South_Wales_USW.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 26,
        showOnHomepage: false,
    },
    {
        id: 27,
        name: "University of the West of England",
        country: "uk",
        logo: "/universities/uk/University_of_the_West_of_England.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 27,
        showOnHomepage: true,
        homepageOrder: 15,
    },
    {
        id: 28,
        name: "London Metropolitan University",
        country: "uk",
        logo: "/universities/uk/London_Metropolitan_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 28,
        showOnHomepage: false,
    },
    {
        id: 29,
        name: "University of Hull (London)",
        country: "uk",
        logo: "/universities/uk/University_of_Hull_London.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 29,
        showOnHomepage: false,
    },
    {
        id: 30,
        name: "Canterbury Christ Church University",
        country: "uk",
        logo: "/universities/uk/Canterbury_Christ_Church_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 30,
        showOnHomepage: false,
    },
    {
        id: 31,
        name: "University of Essex",
        country: "uk",
        logo: "/universities/uk/University_Of_Essex.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 31,
        showOnHomepage: false,
    },
    {
        id: 32,
        name: "Bangor University",
        country: "uk",
        logo: "/universities/uk/bangor.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 32,
        showOnHomepage: false,
    },
    {
        id: 33,
        name: "University College Dublin",
        country: "ireland",
        logo: "/universities/ireland/University_College_Dublin.jpg",
        website: "",
        partnershipType: "direct",
        displayOrder: 33,
        showOnHomepage: false,
    },
    {
        id: 34,
        name: "University College Cork",
        country: "ireland",
        logo: "/universities/ireland/University_College_Cork.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 34,
        showOnHomepage: false,
    },
    {
        id: 35,
        name: "University of Galway",
        country: "ireland",
        logo: "/universities/ireland/University_Of_Galway.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 35,
        showOnHomepage: false,
    },
    {
        id: 36,
        name: "University of Limerick",
        country: "ireland",
        logo: "/universities/ireland/University_Of_Limerick.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 36,
        showOnHomepage: false,
    },
    {
        id: 37,
        name: "Trinity College Dublin",
        country: "ireland",
        logo: "/universities/ireland/Trinity_College_Dublin.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 37,
        showOnHomepage: false,
    },
    {
        id: 38,
        name: "Dublin City University",
        country: "ireland",
        logo: "/universities/ireland/Dublin_City_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 38,
        showOnHomepage: false,
    },
    {
        id: 39,
        name: "Maynooth University",
        country: "ireland",
        logo: "/universities/ireland/Maynooth_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 39,
        showOnHomepage: false,
    },
    {
        id: 40,
        name: "Technological University Dublin",
        country: "ireland",
        logo: "/universities/ireland/Technological_University_Dublin.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 40,
        showOnHomepage: false,
    },
    {
        id: 41,
        name: "Macquarie University",
        country: "australia",
        logo: "/universities/australia/Macquarie_University.jpg",
        website: "",
        partnershipType: "direct",
        displayOrder: 41,
        showOnHomepage: true,
        homepageOrder: 1,
    },
    {
        id: 42,
        name: "Southern Cross University",
        country: "australia",
        logo: "/universities/australia/Southern_Cross_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 42,
        showOnHomepage: false,
    },
    {
        id: 43,
        name: "James Cook University",
        country: "australia",
        logo: "/universities/australia/James_Cook_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 43,
        showOnHomepage: false,
    },
    {
        id: 44,
        name: "University Of New England",
        country: "australia",
        logo: "/universities/australia/University_Of_New_England.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 44,
        showOnHomepage: true,
        homepageOrder: 3,
    },
    {
        id: 45,
        name: "Australian Catholic University",
        country: "australia",
        logo: "/universities/australia/Australian_Catholic_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 45,
        showOnHomepage: true,
        homepageOrder: 3,
    },
    {
        id: 46,
        name: "Charles Darwin University",
        country: "australia",
        logo: "/universities/australia/Charles_Darwin_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 46,
        showOnHomepage: true,
        homepageOrder: 7,
    },
    {
        id: 47,
        name: "University Of Tasmania",
        country: "australia",
        logo: "/universities/australia/University_Of_Tasmania.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 47,
        showOnHomepage: true,
        homepageOrder: 7,
    },
    {
        id: 48,
        name: "University of Wollongong",
        country: "australia",
        logo: "/universities/australia/University_Of_Wollongong_Australia.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 48,
        showOnHomepage: true,
        homepageOrder: 5,
    },
    {
        id: 49,
        name: "Deakin University",
        country: "australia",
        logo: "/universities/australia/Deakin_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 49,
        showOnHomepage: true,
        homepageOrder: 3,
    },
    {
        id: 50,
        name: "La Trobe University",
        country: "australia",
        logo: "/universities/australia/La_Trobe_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 50,
        showOnHomepage: true,
        homepageOrder: 2,
    },
    {
        id: 51,
        name: "Curtin University",
        country: "australia",
        logo: "/universities/australia/Curtin_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 51,
        showOnHomepage: true,
        homepageOrder: 4,
    },
    {
        id: 52,
        name: "Victoria University",
        country: "australia",
        logo: "/universities/australia/Victoria_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 52,
        showOnHomepage: true,
        homepageOrder: 6,
    },
    {
        id: 53,
        name: "Melbourne Institute of Technology",
        country: "australia",
        logo: "/universities/australia/Melbourne_Institute_Of_Technology.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 53,
        showOnHomepage: false,
    },
    {
        id: 54,
        name: "Victoria Institute of Technology",
        country: "australia",
        logo: "/universities/australia/Victoria_Institute_Of_Technology.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 54,
        showOnHomepage: false,
    },
    {
        id: 55,
        name: "University of Notre Dame Australia",
        country: "australia",
        logo: "/universities/australia/University_Of_Notre_Dame_Australia.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 55,
        showOnHomepage: false,
    },
    {
        id: 56,
        name: "The University of Western Australia",
        country: "australia",
        logo: "/universities/australia/The_University_Of_Western_Australia.png",
        website: "",
        partnershipType: "INTO",
        displayOrder: 56,
        showOnHomepage: false,
    },
    {
        id: 57,
        name: "University Of Manitoba",
        country: "canada",
        logo: "/universities/canada/University_Of_Manitoba.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 57,
        showOnHomepage: true,
        homepageOrder: 9,
    },
    {
        id: 58,
        name: "International College Of Manitoba",
        country: "canada",
        logo: "/universities/canada/International_College_Of_Manitoba.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 58,
        showOnHomepage: false,
    },
    {
        id: 59,
        name: "Toronto Metropolitan University",
        country: "canada",
        logo: "/universities/canada/Toronto_Metropolitan_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 59,
        showOnHomepage: false,
    },
    {
        id: 60,
        name: "University Of Windsor",
        country: "canada",
        logo: "/universities/canada/University_Of_Windsor.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 60,
        showOnHomepage: true,
        homepageOrder: 10,
    },
    {
        id: 61,
        name: "Algoma University",
        country: "canada",
        logo: "/universities/canada/Algoma_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 61,
        showOnHomepage: false,
    },
    {
        id: 62,
        name: "Laurentian University",
        country: "canada",
        logo: "/universities/canada/Laurentian_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 62,
        showOnHomepage: false,
    },
    {
        id: 63,
        name: "Lakehead University",
        country: "canada",
        logo: "/universities/canada/Lakehead_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 63,
        showOnHomepage: false,
    },
    {
        id: 64,
        name: "Seneca College",
        country: "canada",
        logo: "/universities/canada/Seneca_College.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 64,
        showOnHomepage: false,
    },
    {
        id: 65,
        name: "Centennial College",
        country: "canada",
        logo: "/universities/canada/Centennial_College.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 65,
        showOnHomepage: false,
    },
    {
        id: 66,
        name: "Memorial University of Newfoundland",
        country: "canada",
        logo: "/universities/canada/Memorial_University_Of_Newfoundland.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 66,
        showOnHomepage: true,
        homepageOrder: 8,
    },
    {
        id: 67,
        name: "Ontario Tech University",
        country: "canada",
        logo: "/universities/canada/Ontario_Tech_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 67,
        showOnHomepage: false,
    },
    {
        id: 68,
        name: "University of Niagara Falls",
        country: "canada",
        logo: "/universities/canada/University_Of_Niagara_Falls.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 68,
        showOnHomepage: false,
    },
    {
        id: 69,
        name: "University of Regina",
        country: "canada",
        logo: "/universities/canada/University_Of_Regina.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 69,
        showOnHomepage: false,
    },
    {
        id: 70,
        name: "Fraser International College (FIC)",
        country: "canada",
        logo: "/universities/canada/Fraser_International_College_(FIC).png",
        website: "",
        partnershipType: "direct",
        displayOrder: 70,
        showOnHomepage: false,
    },
    {
        id: 71,
        name: "University Canada West",
        country: "canada",
        logo: "/universities/canada/University_Canada_West.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 71,
        showOnHomepage: false,
    },
    {
        id: 72,
        name: "Fairleigh Dickinson University",
        country: "canada",
        logo: "/universities/canada/Fairleigh_Dickinson_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 72,
        showOnHomepage: false,
    },
    {
        id: 73,
        name: "Trent University - Ontario",
        country: "canada",
        logo: "/universities/canada/Trent_University_Ontario.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 73,
        showOnHomepage: false,
    },
    {
        id: 74,
        name: "Lambton College - Ontario",
        country: "canada",
        logo: "/universities/canada/Lambton_College_Ontario.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 74,
        showOnHomepage: false,
    },
    {
        id: 75,
        name: "Concordia University of Edmonton",
        country: "canada",
        logo: "/universities/canada/Concordia_University_Of_Edmonton.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 75,
        showOnHomepage: false,
    },
    {
        id: 76,
        name: "Niagara College, Toronto - Ontario",
        country: "canada",
        logo: "/universities/canada/Niagara_College_Toronto.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 76,
        showOnHomepage: false,
    },
    {
        id: 77,
        name: "Fleming College, Toronto - Ontario",
        country: "canada",
        logo: "/universities/canada/Fleming_College_Toronto.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 77,
        showOnHomepage: false,
    },
    {
        id: 78,
        name: "University of Saskatchewan - Saskatchewan",
        country: "canada",
        logo: "/universities/canada/University_Of_Saskatchewan.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 78,
        showOnHomepage: false,
    },
    {
        id: 79,
        name: "Taylor's University",
        country: "malaysia",
        logo: "/universities/malaysia/Taylors_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 79,
        showOnHomepage: true,
        homepageOrder: 16,
    },
    {
        id: 80,
        name: "Asia Pacific University of Technology & Innovation (APU)",
        country: "malaysia",
        logo: "/universities/malaysia/Asia_Pacific_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 80,
        showOnHomepage: false,
    },
    {
        id: 81,
        name: "University Of Wollongong Malaysia",
        country: "malaysia",
        logo: "/universities/malaysia/University_Of_Wollongong_Malaysia.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 81,
        showOnHomepage: false,
    },
    {
        id: 82,
        name: "Curtin University Malaysia",
        country: "malaysia",
        logo: "/universities/malaysia/Curtin_University_Malaysia.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 82,
        showOnHomepage: false,
    },
    {
        id: 83,
        name: "Kuala Lumpur University of Science and Infrastructure",
        country: "malaysia",
        logo: "/universities/malaysia/Kuala_Lumpur_University_Of_Science_And_Infrastructure.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 83,
        showOnHomepage: false,
    },
    {
        id: 84,
        name: "Universiti Teknologi Malaysia",
        country: "malaysia",
        logo: "/universities/malaysia/Universiti_Teknologi_Malaysia.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 84,
        showOnHomepage: false,
    },
    {
        id: 85,
        name: "Swinburne University of Technology Malaysia",
        country: "malaysia",
        logo: "/universities/malaysia/Swinburne_University_Of_Technology_Malaysia.jpg",
        website: "",
        partnershipType: "direct",
        displayOrder: 85,
        showOnHomepage: false,
    },
    {
        id: 86,
        name: "University Of Southampton",
        country: "malaysia",
        logo: "/universities/malaysia/University_Of_Southampton.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 86,
        showOnHomepage: false,
    },
    {
        id: 87,
        name: "Sunway University",
        country: "malaysia",
        logo: "/universities/malaysia/Sunway_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 87,
        showOnHomepage: false,
    },
    {
        id: 88,
        name: "Heriot Watt University",
        country: "malaysia",
        logo: "/universities/malaysia/Heriot_Watt_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 88,
        showOnHomepage: false,
    },
    {
        id: 89,
        name: "INTI International University",
        country: "malaysia",
        logo: "/universities/malaysia/INTI_International_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 89,
        showOnHomepage: false,
    },
    {
        id: 90,
        name: "Yoobee",
        country: "newzealand",
        logo: "/universities/newzealand/Yoobeee.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 90,
        showOnHomepage: false,
    },
    {
        id: 91,
        name: "University Of Waikato",
        country: "newzealand",
        logo: "/universities/newzealand/University_Of_Waikato.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 91,
        showOnHomepage: false,
    },
    {
        id: 92,
        name: "Auckland University Of Technology",
        country: "newzealand",
        logo: "/universities/newzealand/Auckland_University_Of_Technology.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 92,
        showOnHomepage: false,
    },
    {
        id: 93,
        name: "Massey University",
        country: "newzealand",
        logo: "/universities/newzealand/Massey_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 93,
        showOnHomepage: false,
    },
    {
        id: 94,
        name: "Lincoln University",
        country: "newzealand",
        logo: "/universities/newzealand/Lincoln_University.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 94,
        showOnHomepage: false,
    },
    {
        id: 95,
        name: "University Of Auckland",
        country: "newzealand",
        logo: "/universities/newzealand/University_Of_Auckland.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 95,
        showOnHomepage: false,
    },
    {
        id: 96,
        name: "University Of Canterbury",
        country: "newzealand",
        logo: "/universities/newzealand/University_Of_Canterbury.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 96,
        showOnHomepage: false,
    },
    {
        id: 97,
        name: "University Of Otago",
        country: "newzealand",
        logo: "/universities/newzealand/University_Of_Otago.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 97,
        showOnHomepage: false,
    },
    {
        id: 98,
        name: "New Zealand Tertiary College",
        country: "newzealand",
        logo: "/universities/newzealand/New_Zealand_Tertiary_College.png",
        website: "",
        partnershipType: "direct",
        displayOrder: 98,
        showOnHomepage: false,
    },
];
